def test_function():
    def inner_function():
        print("Я текст из внутренней функции!")

    inner_function()

test_function()
#inner_fuction() - ошибка, нет такой функции